### ISSUE TITLE
BUG: Can't connect to kalabox app via Drush without defining db settings in settings.php

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox-issues#229]
Using the following drush alias definition: 

```
$aliases['pressflow7'] = array(
  'root' => '/Users/alec/kalabox/code/pressflow7',
  'uri' => 'pressflow7.kbox',
  'db-url' => 'mysql://kalabox@pressflow7.kbox:49153/kalabox',
  'remote-port' => '3306',
  'db-allows-remote' => TRUE
);
```

I'm not able to use drush commands with my kalabox app until I add db settings to my settings.php:

```
  $databases['default']['default'] = array(
    'driver' => 'mysql',
    'database' => 'kalabox',
    'username' => 'kalabox',
    'password' => '',
    'host' => 'pressflow7.kbox',
    'port' => '49153',
    'prefix' => '',
  );
```

**Comment by pirog** [comment]
I think we can pretty easily create  "local drush" plugin here but we probably want to leave it up to the user to configure their stuff correctly... 

We also could add in SSHd to all our containers so that the local aliases just directly tunnel in over SSH a la pantheon aliases.

**Comment by pirog** [comment]
So i *think* this can actually be addressed in our drush plugin so people will be able to use their local drush if they so choose

**Comment by pirog** [comment]
yeah this is just not going to work locally for pressflow unless you

1. define your own PRESSFLOW_SETTINGS locally
2. add db creds into your settings.php

Im going to backlog this for now since we have the drush container working. Eventually what we will need to do is set up SSH access on our apps and have the local aliases tunnel in that way.
