### ISSUE TITLE
BUG: Ubuntu 12.04 /code folder not being created now

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#242]
Since whatever changes transpired circa 2/12-2/14 kb2 no longer created a /code folder on ubuntu 12.04.  

I can provision just fine, I also restarted 2xs and started anew.  Not 100% sure what is up, I will leave my instance alone in case you need logs, files, etc to diagnose this.

**Comment by pirog** [comment]
By /code you mean /home/user/kalabox/code ?

That folder only gets created when you install and start an app. Did you do
that? What commands did you run? What were thete output?

Seriously. Don't describe your issue like a n00b. Give us useful
information and complete steps to replicate your issue otherwise will be
ignored in favor of ones that are more helpful and don't waste our time by
having us have to do this.

On Sunday, February 15, 2015, John Ouellet <notifications@github.com> wrote:

> Since whatever changes transpired circa 2/12-2/14 kb2 no longer created a
> /code folder on ubuntu 12.04.
>
> I can provision just fine, I also restarted 2xs and started anew. Not 100%
> sure what is up, I will leave my instance alone in case you need logs,
> files, etc to diagnose this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/242>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
Yes @pirog I ran everything per your readme.

**Comment by pirog** [comment]
@bcauldwell:

we are probably going to need to get some VB images for all these OSes pretty soon
