### ISSUE TITLE
Syncthing errors

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#300]

**Comment by pirog** [comment]
https://gist.github.com/joshkoenig/bf8d157f12c5e023b0f9

**Comment by pirog** [comment]
@bcauldwell. havent seen this one before any thoughts?

**Comment by joshkoenig** [comment]
let me know if I can provide any other debugging support

**Comment by bcauldwell** [comment]
In a recent kalabox change a local variable named path was renamed to localPath. This path variable at some point was being serialized for logging. After the change the renaming of the local variable path caused the global variable path (the native nodejs path module) to be serialized instead. Since the global path module contains a circular reference we got this error. I'm putting a change in for it right now.

**Comment by pirog** [comment]
@joshkoenig this should be fixed in 0.3.9 if you want to give it a try before we close this out.
