### ISSUE TITLE
Moving 5GB+ files on syncthing

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#320]
OK

I tried moving a 5GB or so file dump into a drupal site's /sites/default/files area.  

It basically renders my computer almost unusable and / or is taking eons to finish.  After an hour, I have this to show for it:

![kb2-ket](https://cloud.githubusercontent.com/assets/5560907/6561027/8599f638-c664-11e4-8110-c3d026b54f0d.png)

![kb2-kettering](https://cloud.githubusercontent.com/assets/5560907/6561033/8d901494-c664-11e4-9a1e-1f40bf0b3ebb.png)

I know @pirog had said something about using NFS down the road.  But for our larger clients, I cant use their sites in kb2 due to this.

**Comment by pirog** [comment]
NFS could be an option for these larger sites but you are still going to be
pretty slow especially actually running your site.

Add Ben and I to some of your biggest sites so we can test this out.

On Monday, March 9, 2015, John Ouellet <notifications@github.com> wrote:

> OK
>
> I tried moving a 5GB or so file dump into a drupal site's
> /sites/default/files area.
>
> It basically renders my computer almost unusable and / or is taking eons
> to finish. After an hour, I have this to show for it:
>
> [image: kb2-ket]
> <https://cloud.githubusercontent.com/assets/5560907/6561027/8599f638-c664-11e4-8110-c3d026b54f0d.png>
>
> [image: kb2-kettering]
> <https://cloud.githubusercontent.com/assets/5560907/6561033/8d901494-c664-11e4-9a1e-1f40bf0b3ebb.png>
>
> I know @pirog <https://github.com/pirog> had said something about using
> NFS down the road. But for our larger clients, I cant use their sites in
> kb2 due to this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/320>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
You are on Kettering, fiksu,  I added ben@kalamuna.com (shows the old Ben in Pantheon)

I added you to KFP as well

**Comment by pirog** [comment]
I'll try this out tomorrow when i have better internet to download the KFP shiz.

**Comment by pirog** [comment]
NOTE TO SELF: rescan interval may impact this

**Comment by pirog** [comment]
Ok. So i gave this a go as well and can confirm that the experience here is definitely not very good. Unusable is not far off. We definitely need to do some more research into handling these large payloads of files. Some immediate options:

1. Upgrade syncthing, tweak our config (throttling?) 
2. Use another mechanism (nfs?) for handling files, have syncthing just do code.
3. Don't sync files for now... maybe an rsync plugin as a stop gap?

I also want to get a little more clarify on what is happening here. @labboy0276 it would be good for you to try to replicate this and see if you get the same.

1. Spun up D7 app example
2. kbox git clone kfp 
3. imported database via mysql
4. dropped in the 5GB of files

Maybe 2-3 minutes in it appears to get stuck. At this point if you open up VirtualBox it reports its status as "aborted". Everything seems to be going pretty slow at this point since hte local syncthing is still busy presumably indexing files. 

You can turn the KB2 box back on and restart the app and it will resume syncthing but will crash in the same way as above eventually. 

Can you confirm this is what happens on your end as well?

**Comment by pirog** [comment]
Going to try this with rsync to see if that can naturally throttle things

**Comment by pirog** [comment]
Ok so im using rysnc here and it seems to work a lot better but i'll let you know for sure when it is done. I still get pretty high CPU usage but we can do things to mitigate that.

this is a relief since when we have all the conncetors in place people are generally going to be doing this  generally going to be doing rsync of stfp behind the scenes for this instead of a tar dump.

Using the rysnc docs on pantheon for this particular test
https://pantheon.io/docs/articles/local/rsync-and-sftp/

**Comment by pirog** [comment]
This got pretty far but then ultimately crashed :(

**Comment by pirog** [comment]
so the keys here are to use rsync and not have the GUI open ... that seems to do the trick. That means you kind of need to run in silent mode until we have better stuff set up for pushing and pulling sites

**Comment by pirog** [comment]
@labboy0276... for now i think this would be best expressed in the documentation somewhere. Do you think you can maybe create a brief wiki page about how to do this based on your experience that we can direct people to?

**Comment by labboy0276** [comment]
I can do it!

I will do it this weekend

On Fri, Mar 13, 2015 at 5:25 PM, Mike Pirog <notifications@github.com>
wrote:

> @labboy0276 <https://github.com/labboy0276>... for now i think this would
> be best expressed in the documentation somewhere. Do you think you can
> maybe create a brief wiki page about how to do this based on your
> experience that we can direct people to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/320#issuecomment-79417665>
> .
>



-- 
*John Ouellet*
*Developer & Support Manager*
415-470-3076
www.kalamuna.com

**Comment by pirog** [comment]
Ultimately it might not be worth syncing all these media files. See #298

**Comment by heathdutton** [comment]
Since we needed to start supporting retina resolutions and fluid designs with heavy photography the minimum resolutions required have skyrocketed. Now, after 1~2 years of use by a brand a typical site might have 40k+ files (after imagecache & picture divvy up the breakpoint renderings) weighing in at over 12GB.

We simply don't have enough room on our local machines to have duplicate coppies of these sites. Not to mention that file counts that high are likely too heavy to be practical with Syncthing. 

Sadly, this limitation makes kalabox an unusable platform for us at the moment.

I am intrigued by the option of using NFS for the file folders, and Syncthing for the code. That sounds rather logical, and possibly the best road to take. Has this been attempted?

@labboy0276 is that documentation out there somewhere?

**Comment by labboy0276** [comment]
Hello,

This issue is no longer an issue, it was changed a couple months ago.  What transpired from this issue is that syncthing no longer tracks the files directory.  So now, you can have massive file directories and it really does not matter.  You use the kalabox rsync plugin to port your files into the container.

Also, you can have syncthing ignore certain directoried too with shareIgnore in the kalabox.json.  The default setup is this:

```
  "shareIgnores": [
    "sites/default/files/*",
    ".git"
  ],
```

So now you can use kalabox2 just fine with your setup.  I hope this helps you understand this a little better.  If not, please let me know.

**Comment by pirog** [comment]
@heathdutton figuring out how to handle file sharing/syncing has def been one of the harder problems we've addressed thus far. 

We initially started with just NFS for everything but it was VERY slow and our ability to do tuning there was prohibited by the fact that this is a risky area to try to manage when you are doing it to someone elses computer. 

As of right now there are four basic scenarios that we see playing out on the file sharing front

1. Stick with syncthing and hope that when it is stable it can handle > 3GB
2. Swap out syncthing for some TBD ideal sharing/syncing technology
3. Do some sort of combo of syncthing/nfs in the way you describe.
4. Do what we are doing now aka ignoring media directories.

We want to get some more user feedback before we decide but we consider this to be a top priority.
